#!/bin/sh

common_args="--oknodo --name aesdsocket"
d_stop() {
	start-stop-daemon -K ${common_args} -s TERM

}
d_start() {
	start-stop-daemon -S ${common_args} --startas /usr/bin/aesdsocket -- -d
}

case "$1" in
	start)
		echo "starting aesd-socket-start-stop daemon"
		d_start
		;;
	stop)
		d_stop
		;;
	*)
		echo "Usage: $0 start|stop"
		exit 1
esac
exit 0
